const https = require("https");
const http = require("http");
function fn(ctx) {
    switch (ctx.action.action) {
        case 'wget':
            //code here
            let content = "";
            https.get(action.url, (res) => {
                res.setEncoding('utf-8');
                res.on('data', (d) => {
                    content += d;
                });
                res.on('end', () => {
                    fs.writeFileSync(path.join(dirname, action.file), content, "utf8");
                });
            }).on('error', (error) => { console.error(error); });
            break;
        case 'server':
            var server = http.creatServer((req, res) => {
                res.writeHead(200, { 'Content-Type': 'text/plain' });
                res.end(varCheck(action.content));
            });
            server.listen(action.port);
            break;
    }
}